updated jfrog -block

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -43,6 +43,10 @@ pipeline {
                     echo 'Building Docker image...'
                     sh """
                         docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f docker/Dockerfile .
+                        if [ $? -ne 0 ]; then
+                        echo "Docker build failed"
+                        exit 1
+                        fi
                     """
                 }
             }
@@ -59,6 +63,8 @@ pipeline {
         stage('Push Docker Image to Artifactory') {
             steps {
                 script {
+                    // Verify the built image is listed
+                    sh "docker images"
                     // Tag the image
                     sh """
                         docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_REGISTRY}/${DOCKER_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
